# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-21 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name_plural': 'Global Settings'},
        ),
    ]
