# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerpay', '0003_auto_20210122_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('api_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('key_test', 'Key test')], max_length=255, unique=True),
        ),
    ]
