# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-25 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgerpay', '0004_auto_20210125_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='api_url',
            field=models.URLField(verbose_name='API URL'),
        ),
    ]
